ffmpeg_path: ./ffmpeg/ffmpeg.exe
notes_slides:
- 1
- 2
presentations:
  教學簡報測試:
    notes_slides:
    - 1
    - 2
    - 680
    - 681
  測試:
    notes_slides:
    - 1
    - 2
subtitle_config:
  說明:
    opener: 以下說明此原則的內容。
    closer: ''
    read_shapes: false
    read_table: true
  設定方法:
    opener: 以下介紹本原則的設定方法。
    closer: ''
    read_shapes: false
    read_table: false
  Azure 入口網站操作示意圖:
    opener: 本頁介紹 Azure 入口網站的操作步驟，
    closer: ''
    read_shapes: true
    read_table: false
  Azure CLI設定方法:
    opener: 本頁介紹 Azure CLI 的設定方法，
    closer: 執行結果如圖所示。
    read_shapes: false
    read_table: false
  PowerShell設定方法:
    opener: 本頁介紹 PowerShell 的設定方法，
    closer: 執行結果如圖所示。
    read_shapes: false
    read_table: false
  default:
    opener: 本頁介紹相關內容，
    closer: ''
    read_shapes: false
    read_table: false
table_prefix: 此原則支援以下設定方法：
table_supported_symbols:
- ☑
- ✓
- ✔
- V
- v
- O
- o
continuation_opener: 接續上頁，
pause_between_paragraphs_ms: 125
tts_voice: zh-TW-HsiaoChenNeural
tts_batch_size: 20
export_dpi: 200
video_fps: 12
